version: '3.9'

services:
  web-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-api
    restart: always
    volumes:
      - /root/DB:/app/DB
    ports:
      - "5100:5100"
    environment:
      - ConnectionStrings__SQLiteConnection=Data Source=/app/DB/LoginApp.db
