version: '3.9'

services:
  web-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-api
    restart: always
    volumes:
      - ./DB:/app/DB
    ports:
      - "8080:8080"